name: Auto Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  auto_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: 추출 버전 정보
      id: extract_version
      run: echo "::set-output name=version::$(jq -r .version manifest.json)"

    - name: 병합 .gitignore + .ignore_release
      id: merge_ignore_files
      run: |
        if [ -f .ignore_release ]; then
          cat .ignore_release >> .gitignore
        fi
    
    - name: 불필요한 파일 및 폴더 삭제
      run: |
        # 병합된 .gitignore 및 .ignore_release 파일에 해당하는 모든 파일 및 폴더를 삭제합니다.
        cat .gitignore | sed '/^#.*/ d' | sed '/^\s*$/ d' | sed 's/^/git rm -r /' | bash || true
        rm .gitignore
    
    - name: 릴리즈 압축 파일 생성
      run: |
        # 현재 폴더의 모든 파일을 압축합니다.
        zip -r v${{ steps.extract_version.outputs.version }}.zip . -x ".git/*"

    - name: 나이트 압축 파일 생성
      run: |
        # 압축된 파일을 복사하여 수정합니다.
        cp v${{ steps.extract_version.outputs.version }}.zip v${{ steps.extract_version.outputs.version }}-nightly.zip

        # manifest.json 파일에서 "name"을 수정합니다.
        jq '.name = "백준허브 Nightly(BaekjoonHub Nightly)"' manifest.json > manifest.tmp.json
        mv manifest.tmp.json manifest.json

        # assets/thumbnail.png 파일을 색상을 반전시켜 수정합니다.
        convert assets/thumbnail.png -negate assets/thumbnail-night.png
        mv assets/thumbnail-night.png assets/thumbnail.png

        # 압축 파일에 변경된 파일을 추가합니다.
        zip -u v${{ steps.extract_version.outputs.version }}-nightly.zip manifest.json assets/thumbnail.png

    - name: 릴리즈 생성
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: v${{ steps.extract_version.outputs.version }}.zip, v${{ steps.extract_version.outputs.version }}-nightly.zip
        tag_name: v${{ steps.extract_version.outputs.version }}
        release_name: v${{ steps.extract_version.outputs.version }}
        body: ''
